import type { Metadata } from "next";
import { Alexandria, Sen } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "next-themes";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});

const sen = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${alexandria.variable} ${sen.variable} antialiased`}>
        <ThemeProvider attribute="data-theme" defaultTheme="light" 
          enableSystem={false}
          disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
